require("core.options").load()
require("core.mappings").load()
require("core.plugins").load()

require("modules.statusline").load()
require("modules.sidebar").load()
require("modules.git").load()
require("modules.commenter").load()
require("modules.completion").load()
require("modules.markdown").load()
